# Generated by Django 5.0.7 on 2024-08-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("weather", "0001_initial"),
        ("weather", "0002_citysearchhistory_last_searched_and_more"),
        ("weather", "0003_citysearchhistory_temperature"),
        ("weather", "0004_remove_citysearchhistory_search_count"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitySearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("search_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("temperature", models.FloatField(default=18.0)),
            ],
        ),
    ]
