# Generated by Django 5.0.7 on 2024-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="citysearchhistory",
            name="last_searched",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="citysearchhistory",
            name="search_count",
            field=models.IntegerField(default=0),
        ),
    ]
