# Generated by Django 5.0.7 on 2024-08-10 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_citysearchhistory_temperature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citysearchhistory",
            name="search_count",
        ),
    ]
