version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./weather_project:/weather_project
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=*
      - REDIS_HOST=redis


  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"