FROM python:3.12.4-slim

WORKDIR /weather_project

EXPOSE 8000

COPY pyproject.toml poetry.lock ./
RUN pip install poetry
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-root

COPY . .

CMD ["poetry", "run", "gunicorn", "--bind", "0.0.0.0:8000", "weather_project.wsgi:application", "--timeout", "120"]
